---
abstract: 'Authenticate against OAuth2 providers'
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-OAuth2
no_index:
  directory:
    - t
    - inc
    - t
requires:
  IO::Socket::SSL: 0
  Mojolicious: 1.64
  perl: 5.008007
resources:
  bugtracker: http://github.com/marcusramberg/mojolicious-plugin-oauth2/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/marcusramberg/mojolicious-plugin-oauth2
version: 1.1
