--- #YAML:1.0
name:               Mojolicious-Plugin-OAuth2
version:            0.4
abstract:           Authenticate against OAuth2 providers
author:
    - Marcus Ramberg <mramberg@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Mojolicious:  1.64
    perl:         5.008007
resources:
    bugtracker:  http://github.com/kraih/mojolicious-plugin-oauth2/issues
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/kraih/mojolicious-plugin-oauth2
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
